FROM registry.access.redhat.com/ubi9/ubi

USER root

RUN dnf install -y python3 python3-pip git; dnf clean all
RUN python3 -m pip install --upgrade pip

WORKDIR /app

COPY ./ /app/
RUN python3 -m pip install -r requirements.txt

RUN chown -R 1001:0 /app && \
    chmod -R g=u /app

USER 1001

ENTRYPOINT ["python3"]
CMD ["sensor-http.py"]